### ISSUE TITLE
Cannot receiver code in other-TG-client or SMS Code in my iPhone

### ISSUE THREAD

**Issue by thxbrop** [nicegram/Nicegram-iOS#141]
### Checklist
- [x] I am reporting an issue in existing functionality that does not work as intended
- [x] I've searched for existing [GitHub issues](https://github.com/telegrammessenger/Telegram-iOS/issues)

### Description
I am trying to log in the Nicegram with Chinese Phone Number in my iPhone.

### Expected Behavior
My other available TG-clients should receiver code or my phone should receiver SMS-code.

### Actual Behavior
Did not receive but it's working when I try these steps in [online telegram client](https://web.telegram.org/k).

### Steps to Reproduce
1. Enter my Chinese Phone number.
2. Send code or SMS-code.
### Environment
**Device:** `iPhone 14`

**iOS version:** `16.2`

**App version:** `1.1.8`

**Comment by MaGua-Bishop** [comment]
这个不是nicegram的问题，在我上个月测试的时候就已经发现，中国手机号已经全部收不到推特 tg 哪怕是游戏相关的国外网站验证码也是没办法收到的，这个中国政府的问题

**Comment by thxbrop** [comment]
> 这个不是nicegram的问题，在我上个月测试的时候就已经发现，中国手机号已经全部收不到推特 tg 哪怕是游戏相关的国外网站验证码也是没办法收到的，这个中国政府的问题

好吧
