### ISSUE TITLE
Nicegram is no longer open source!

### ISSUE THREAD

**Issue by NyaMisty** [nicegram/Nicegram-iOS#164]
### Checklist
- [x] I am reporting an issue in existing functionality that does not work as intended
- [x] I've searched for existing [GitHub issues](https://github.com/telegrammessenger/Telegram-iOS/issues)

### Description
The new swift package nicegram-assistant-ios aren't public, and thus making Nicegram a non-opensource client, causing all 3rd party Nicegram build failing. That's disappointing.

See: https://github.com/nicegram/Nicegram-iOS/blob/def7aecfe59671bf5467cd912fdc2167eb690625/swift_deps.bzl#L41
```
    # branch: develop
    swift_package(
        name = "swiftpkg_nicegram_assistant_ios",
        commit = "74a903bbc75af22ef19aa77ab20ba8df1ae0de27",
        dependencies_index = "@//:swift_deps_index.json",
        remote = "git@bitbucket.org:mobyrix/nicegram-assistant-ios.git",
    )
```

**Comment by swiftyspiffy** [comment]
Related: https://github.com/nicegram/Nicegram-iOS/issues/157

**Comment by ssheleg** [comment]
> ### Checklist
> * [x]  I am reporting an issue in existing functionality that does not work as intended
> * [x]  I've searched for existing [GitHub issues](https://github.com/telegrammessenger/Telegram-iOS/issues)
> 
> ### Description
> The new swift package nicegram-assistant-ios aren't public, and thus making Nicegram a non-opensource client, causing all 3rd party Nicegram build failing. That's disappointing.
> 
> See:
> 
> https://github.com/nicegram/Nicegram-iOS/blob/def7aecfe59671bf5467cd912fdc2167eb690625/swift_deps.bzl#L41
> 
> ```
>     # branch: develop
>     swift_package(
>         name = "swiftpkg_nicegram_assistant_ios",
>         commit = "74a903bbc75af22ef19aa77ab20ba8df1ae0de27",
>         dependencies_index = "@//:swift_deps_index.json",
>         remote = "git@bitbucket.org:mobyrix/nicegram-assistant-ios.git",
>     )
> ```

We are making open source everything related to messages and other personal information of users to demonstrate that we do not violate confidentiality. Separate enhancement blocks like the Assistant cannot be made open source as they carry high value in terms of intellectual property, but since they are not related to the personal data of Telegram users, we reserve the right not to disclose the source code of our own developments.

**Comment by ssheleg** [comment]
You can use the original source code of Telegram if you want to build your own client. If you want to suggest improvements or help in fixing bugs, we will be happy to accept it! To do this, please contact our support and report the issue you have found. We will try to resolve it as quickly as possible.

**Comment by 0n1cOn3** [comment]
> > ### Checklist
> 
> > * [x]  I am reporting an issue in existing functionality that does not work as intended
> 
> > * [x]  I've searched for existing [GitHub issues](https://github.com/telegrammessenger/Telegram-iOS/issues)
> 
> > 
> 
> > ### Description
> 
> > The new swift package nicegram-assistant-ios aren't public, and thus making Nicegram a non-opensource client, causing all 3rd party Nicegram build failing. That's disappointing.
> 
> > 
> 
> > See:
> 
> > 
> 
> > https://github.com/nicegram/Nicegram-iOS/blob/def7aecfe59671bf5467cd912fdc2167eb690625/swift_deps.bzl#L41
> 
> > 
> 
> > ```
> 
> >     # branch: develop
> 
> >     swift_package(
> 
> >         name = "swiftpkg_nicegram_assistant_ios",
> 
> >         commit = "74a903bbc75af22ef19aa77ab20ba8df1ae0de27",
> 
> >         dependencies_index = "@//:swift_deps_index.json",
> 
> >         remote = "git@bitbucket.org:mobyrix/nicegram-assistant-ios.git",
> 
> >     )
> 
> > ```
> 
> 
> 
> Separate enhancement blocks like the Assistant cannot be made open source as they carry high value in terms of intellectual property, 

> but since they are not related to the personal data of Telegram users, we reserve the right not to disclose the source code of our own developments.

This may be true, but does not allow compiling = does not make the project trustworthy = is discarded by the FOSS community. And also no longer recommended. The Nicegram Assistant has only been a burden for me as an ex Nicegram user. The same with the AI tools. 


Fortunately, the initiator of Nicegram has abandoned the sinking ship and released Swiftgram without all this nonsense and is completely transparent with the source code. 

Nicegram used to be good until AI and Assistant were introduced. After that, crashes became 10-15 times more frequent, which is simply not tolerated.
